import { AppDatabase } from './models';

const now = new Date();
const plusHours = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
const minusHours = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();

export const seedDatabase: AppDatabase = {
  tenants: [
    {
      id: 'tenant_idea',
      name: 'Osiedle IDEA',
      slug: 'osiedle-idea',
    },
  ],
  users: [
    {
      id: 'user_anna',
      tenantId: 'tenant_idea',
      role: 'resident',
      fullName: 'Anna Kowalska',
      email: 'anna@ideapark.local',
      password: 'demo123',
      apartmentNumber: 'A-101',
      phone: '+48 600 100 100',
      ownedSpaceIds: ['space_p1_014'],
      vehicleIds: ['vehicle_anna_1', 'vehicle_anna_2'],
    },
    {
      id: 'user_jan',
      tenantId: 'tenant_idea',
      role: 'resident',
      fullName: 'Jan Nowak',
      email: 'jan@ideapark.local',
      password: 'demo123',
      apartmentNumber: 'B-208',
      phone: '+48 600 200 200',
      ownedSpaceIds: [],
      vehicleIds: ['vehicle_jan_1'],
    },
    {
      id: 'user_admin',
      tenantId: 'tenant_idea',
      role: 'admin',
      fullName: 'Marta Zielinska',
      email: 'admin@ideapark.local',
      password: 'demo123',
      apartmentNumber: 'ADMIN',
      phone: '+48 600 300 300',
      ownedSpaceIds: [],
      vehicleIds: [],
    },
    {
      id: 'user_operator',
      tenantId: 'tenant_idea',
      role: 'operator',
      fullName: 'Operator Centralny',
      email: 'operator@ideapark.local',
      password: 'demo123',
      apartmentNumber: 'HQ',
      phone: '+48 600 400 400',
      ownedSpaceIds: [],
      vehicleIds: [],
    },
  ],
  vehicles: [
    {
      id: 'vehicle_anna_1',
      userId: 'user_anna',
      plate: 'WA1234A',
      label: 'BMW iX',
      color: 'Szary grafit',
    },
    {
      id: 'vehicle_anna_2',
      userId: 'user_anna',
      plate: 'WA7777K',
      label: 'Mini Cooper',
      color: 'Perlowa biel',
    },
    {
      id: 'vehicle_jan_1',
      userId: 'user_jan',
      plate: 'WX9912N',
      label: 'Tesla Model 3',
      color: 'Niebieski',
    },
  ],
  spaces: [
    {
      id: 'space_p1_014',
      tenantId: 'tenant_idea',
      code: 'P1-014',
      zone: 'Poziom -1',
      level: '-1',
      type: 'private',
      ownerId: 'user_anna',
      isBlocked: false,
      notes: 'Slup po lewej stronie',
    },
    {
      id: 'space_p1_021',
      tenantId: 'tenant_idea',
      code: 'P1-021',
      zone: 'Poziom -1',
      level: '-1',
      type: 'shared',
      ownerId: null,
      isBlocked: false,
      notes: 'Blisko windy A',
    },
    {
      id: 'space_p1_033',
      tenantId: 'tenant_idea',
      code: 'P1-033',
      zone: 'Poziom -1',
      level: '-1',
      type: 'guest',
      ownerId: null,
      isBlocked: false,
      notes: 'Goscinne 24/7',
    },
    {
      id: 'space_p2_012',
      tenantId: 'tenant_idea',
      code: 'P2-012',
      zone: 'Poziom -2',
      level: '-2',
      type: 'guest',
      ownerId: null,
      isBlocked: false,
      notes: 'Szerokie miejsce',
    },
    {
      id: 'space_p2_099',
      tenantId: 'tenant_idea',
      code: 'P2-099',
      zone: 'Poziom -2',
      level: '-2',
      type: 'shared',
      ownerId: null,
      isBlocked: true,
      notes: 'Tymczasowo zablokowane',
    },
  ],
  shareWindows: [
    {
      id: 'share_anna_now',
      tenantId: 'tenant_idea',
      spaceId: 'space_p1_014',
      ownerId: 'user_anna',
      startsAt: minusHours(1),
      endsAt: plusHours(6),
      createdAt: minusHours(2),
    },
  ],
  reservations: [
    {
      id: 'res_jan_done',
      tenantId: 'tenant_idea',
      spaceId: 'space_p1_021',
      userId: 'user_jan',
      vehicleId: 'vehicle_jan_1',
      startsAt: minusHours(5),
      endsAt: minusHours(3),
      status: 'completed',
      createdAt: minusHours(6),
    },
    {
      id: 'res_jan_upcoming',
      tenantId: 'tenant_idea',
      spaceId: 'space_p1_021',
      userId: 'user_jan',
      vehicleId: 'vehicle_jan_1',
      startsAt: plusHours(2),
      endsAt: plusHours(4),
      status: 'upcoming',
      createdAt: minusHours(1),
    },
  ],
  guests: [
    {
      id: 'guest_1',
      tenantId: 'tenant_idea',
      hostId: 'user_anna',
      guestName: 'Piotr Lis',
      plate: 'WPR9090K',
      validFrom: plusHours(2),
      validTo: plusHours(8),
      qrCode: 'IDP-GUEST-PIOTR-9090',
      status: 'active',
      createdAt: minusHours(1),
    },
  ],
  gateEvents: [
    {
      id: 'gate_1',
      tenantId: 'tenant_idea',
      actorId: 'user_admin',
      gateName: 'Brama garazowa A',
      openedAt: minusHours(3),
      status: 'opened',
    },
  ],
  auditLogs: [
    {
      id: 'audit_1',
      tenantId: 'tenant_idea',
      actorId: 'user_jan',
      action: 'reservation.created',
      details: {
        spaceId: 'space_p1_021',
        code: 'P1-021',
      },
      createdAt: minusHours(1),
    },
    {
      id: 'audit_2',
      tenantId: 'tenant_idea',
      actorId: 'user_anna',
      action: 'share.created',
      details: {
        spaceId: 'space_p1_014',
        code: 'P1-014',
      },
      createdAt: minusHours(2),
    },
  ],
};
